---
# tasks file for node_exporter
- name: Stop service node_exporter, if started
  ansible.builtin.systemd_service:
    name: node_exporter.service
    state: stopped
  ignore_errors: true

- name: Create configs directory
  file:
    path: "{{ dir }}/node_exporter"
    state: directory

- name: Copy service for node_exporter
  copy:
    src: "node_exporter"
    dest: "{{ dir }}/node_exporter"
    force: yes
    mode: 0755

- name: Copy service file for node_exporter
  ansible.builtin.template:
    src: "node_exporter.service.j2"
    dest: "{{ sysdir }}/node_exporter.service"
    force: yes

- name: Add the user
  ansible.builtin.user:
    name: "{{ user }}"
    group: "{{ group }}"

- name: Change file ownership and group
  ansible.builtin.file:
    path: "{{ dir }}/node_exporter"
    owner: "{{ user }}"
    group: "{{ group }}"
    recurse: true

- name: Run service node_exporter
  ansible.builtin.systemd_service:
    name: node_exporter.service
    state: started
    daemon_reload: true
    enabled: true